---
- name: Copy file from local host to remote clients
  hosts: all

  tasks:
    - name: Copying file
      become: true
      copy:
        src: /home/terrel/some/cfg
        dest: /tmp
        mode: 0644
